name = "maeon-craft-landing"
compatibility_date = "2025-06-01"
compatibility_flags = ["nodejs_compat"]
account_id = "a5eabdc2b11aae9bd5af46bd6a88179e"
workers_dev = true

# Custom domain
routes = [
  { pattern = "maeoncraft.buildwithoracle.com", custom_domain = true }
]

[assets]
directory = "./dist"
